import type { AppProps } from 'next/app'
import Head from 'next/head'

import { Compose } from 'src/components'
import { ThemeContextProvider } from 'src/contexts'

import 'src/styles/globals.scss'

function GoogleSearch({ Component, pageProps }: AppProps) {
  return (
    <Compose components={[ThemeContextProvider]}>
      <Head>
        <title>Google Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Compose>
  )
}

export default GoogleSearch
