const ResultsArray = [
  'Languages',
  {
    title: 'JavaScript/TypeScript',
    percent: 100,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'Dart',
    percent: 85,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'HTML & CSS',
    percent: 84,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'Java',
    percent: 75,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'SQL',
    percent: 70,
    proficiency: 'Advanced',
    color: '#ffc107',
  },
  {
    title: 'Elixir',
    percent: 65,
    proficiency: 'Intermediate',
    color: '#ffc107',
  },
  {
    title: 'Python',
    percent: 60,
    proficiency: 'Intermediate',
    color: '#ffc107',
  },
  {
    title: 'Golang',
    percent: 55,
    proficiency: 'Intermediate',
    color: '#ffc107',
  },
  {
    title: 'C',
    percent: 50,
    proficiency: 'Intermediate',
    color: '#ffc107',
  },
  {
    title: 'Ruby',
    percent: 38,
    proficiency: 'Intermediate',
    color: '#dc3545',
  },
  {
    title: 'Shell',
    percent: 35,
    proficiency: 'Familiar',
    color: '#dc3545',
  },
  'Frameworks & Technologies',
  {
    title: 'React',
    percent: 100,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'Redux',
    percent: 100,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'React Native',
    percent: 97,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'Firebase',
    percent: 94,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'Deno & Node',
    percent: 92,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'MongoDB',
    percent: 84,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'Flutter',
    percent: 80,
    proficiency: 'Advanced',
    color: '#00a1a7',
  },
  {
    title: 'PostgreSQL',
    percent: 70,
    proficiency: 'Advanced',
    color: '#ffc107',
  },
  {
    title: 'Docker',
    percent: 67,
    proficiency: 'Intermediate',
    color: '#ffc107',
  },
  {
    title: 'Kubernetes',
    percent: 60,
    proficiency: 'Intermediate',
    color: '#ffc107',
  },
  {
    title: 'Phoenix (Elixir)',
    percent: 50,
    proficiency: 'Intermediate',
    color: '#ffc107',
  },
  {
    title: 'Helm (k8s)',
    percent: 43,
    proficiency: 'Familiar',
    color: '#ffc107',
  },
  {
    title: 'Rails',
    percent: 40,
    proficiency: 'Familiar',
    color: '#ffc107',
  },
  {
    title: 'Vue',
    percent: 40,
    proficiency: 'Familiar',
    color: '#ffc107',
  },
  {
    title: 'Pytorch',
    percent: 37,
    proficiency: 'Familiar',
    color: '#ffc107',
  },
  {
    title: 'OpenCV',
    percent: 32,
    proficiency: 'Familiar',
    color: '#dc3545',
  },
  {
    title: 'Flask',
    percent: 30,
    proficiency: 'Familiar',
    color: '#dc3545',
  },
  {
    title: 'Spring',
    percent: 20,
    proficiency: 'Familiar',
    color: '#dc3545',
  },
];

export default ResultsArray;
